### ISSUE TITLE
Marathon: Be able to assign instances via variable

### ISSUE THREAD

**Issue by jrx** [dcos-labs/ansible-dcos-module#3]
Broken because of: https://github.com/ansible/ansible/issues/9362

The following example is not possible:

```
- name: Ensure Marathon-LB is installed
  dcos_package:
    name: marathon-lb
    app_id: marathon-lb
    version: 1.12.2
    state: present
    options:
      marathon-lb:
        instances: "{{ groups['agents_public'] | length }}"
```
